.github/workflows/test.yml
README.md
deps.ts
pages/import-map.json
scripts.json

denonで実行できるようにする

---

.github/workflows/deploy_release.yml

Releaseされたとき、
- タグ名でブランチを作成する
- ビューアのキャッシュ-rオプション付きでをとる（古いキャッシュが残っていると動かない場合がよくあるため）
- サービス再起動
という流れでデプロイします

Release時に自動でサーバにデプロイされるように

---

api/test/security_test.ts
deps.ts
server.ts

`OPTIONS`メゾットによるプリフライトで適切なヘッダを返すようになりました。

CORS用のヘッダを追加

---

v1/parts/firestore_opration.ts
v1/test/restore_test.ts

Deno 1.16.0に対応

---

deps.ts
v1/match.ts
v1/parts/ai-list.ts
v1/parts/expKakomimasu.ts

Deno deployで使えるようにするため
Fix #12
**実装方法**
client_ax.jsのClientAxクラスをgame.aiに登録し、
ゲーム開始時に`onInit`、ターン更新時に`onTurn`を呼び出した。

fix(match): ai戦に使用するaiをサブプロセスで動かさない方法に変更

---

CHANGELOG.md

fix(docs): update CHANGELOG

---

client/client.ts
client/test/apiclient_test.ts
deps-test.ts
deps.ts
v1/test/auth_test.ts
v1/test/flow_test.ts
v1/test/freeMatch_flow_test.ts
v1/test/game_test.js
v1/test/match_test.js
v1/test/post-api_test.ts
v1/test/restore_test.ts
v1/test/security_test.ts
v1/test/tournaments_test.js
v1/test/users_test.js
v1/test/util_test.ts

fix(client): kakomimasu/client-jsのコードをserver内に移動

---

.github/workflows/pr_labeler.yml

PRタイトルの最初の文字が`fix|feat|chore|docs|refactor|test` の時にそれに応じたラベルを生成するようにしました。
プレフィックスはここを参考にしています。
https://www.conventionalcommits.org/ja/v1.0.0-beta.4/

test(ci): PR作成時にラベルを生成するGithub actionsを追加

---

.github/workflows/pr_labeler.yml
.github/workflows/test.yml
deps.ts
v1/parts/firestore_opration.ts

Fix(v1): firebaseの型定義を追加しました

---

client/client.ts
client/test/apiclient_test.ts
v1/test/users_test.js

fix(client): 接続先が見つからない場合に例外ではなく適切な戻り値を返すように修正

---

envconfig.yml
server.ts

feat: サーバのバージョンを返すAPIを作る

---

server.ts
v1/error.ts
v1/test/security_test.ts

feat: 存在しないパスにアクセスしたときのレスポンスを付ける

---

v1/ws.ts

ビューアのゲーム詳細でWebsocketが切れるのはHeroku側で接続が切られていたからだそうです。
https://devcenter.heroku.com/articles/http-routing#timeouts
定期的にメッセージを送ることで解決しました。

fix(v1/ws): Websocket接続でherokuにH15エラーで切断されるバグを修正

---

v1/game.ts
v1/match.ts
v1/parts/expKakomimasu.ts
v1/types.ts
v1/util.ts
v1/ws.ts

fix(v1/ws): WebSocket APIの仕様・アルゴリズム変更

---

deps-test.ts
server.ts
v1/parts/expKakomimasu.ts
v1/test/restore_test.ts

Firebase関連のバグを修正
Fix #141 
Fix #136

fix(expKakomimasu): firebaseデータのrestoreバグ修正、保存内容を変更

---

.github/workflows/heroku_deploy.yml

ci: Add Heroku deploy actions

---

client/client.ts

types.tsを整理する

---

v1/match.ts
v1/test/match_test.js

fix(v1/match/id/action): actionsがnullのときの処理を追加

---

core/expKakomimasu.ts
miyakonojo/_matches.ts
miyakonojo/test/match.test.ts
miyakonojo/types.ts
tomakomai/_util.ts
v1/match.ts
v1/test/match_test.js
v1/test/sample/afterAction_sample.json
v1/test/sample/afterAction_sample2.json
v1/test/sample/matchGameInfo_sample.json
v1/test/sample_guest/afterAction_sample.json
v1/test/sample_guest/afterAction_sample2.json
v1/test/sample_guest/matchGameInfo_sample.json
v1/types.ts

feat(v1): Playerのタイプフィールドを追加

---

core/env.ts
deps-test.ts
deps.ts

~~renderでdeployがfailしてしまう問題を解決中...
（firebaseにつながらない）~~
モジュールをアップデートしたらとりあえずは安定してデプロイ成功するようになりました。

build(deps): update dependencies

---

.github/workflows/test.yml
Dockerfile

Revert "firebase admin用にdenoのダウングレード1.33.0"

---

.github/workflows/test.yml
Dockerfile
client/types.ts
core/expKakomimasu.ts
deno.jsonc
test.ts
v1/_matches.ts
v1/parts/openapi.ts
v1/test/flow_guest_test.ts
v1/test/flow_test.ts
v1/test/freeMatch_flow_test.ts
v1/test/matches.test.js

以下のオプションを両APIで指定可能にしました．
Fix #146 
- nAgent
- nPlayer
- totalTurn
- operationSec
- transitionSec

feat(v1/matches,v1/matches/ai/players): ゲームの作成オプションを指定できるように変更
